export enum DisputeStatus {
  OPEN              = 'OPEN',
  UNDER_REVIEW      = 'UNDER_REVIEW',
  AWAITING_EVIDENCE = 'AWAITING_EVIDENCE',
  RESOLVED_RENTER   = 'RESOLVED_RENTER',
  RESOLVED_VENDOR   = 'RESOLVED_VENDOR',
  ESCALATED         = 'ESCALATED',
  CLOSED            = 'CLOSED',
}

export enum DisputeType {
  DAMAGE_CLAIM       = 'DAMAGE_CLAIM',
  ITEM_NOT_RETURNED  = 'ITEM_NOT_RETURNED',
  ITEM_NOT_AS_DESCRIBED = 'ITEM_NOT_AS_DESCRIBED',
  DEPOSIT_DISPUTE    = 'DEPOSIT_DISPUTE',
  PAYMENT_DISPUTE    = 'PAYMENT_DISPUTE',
  VENDOR_NO_SHOW     = 'VENDOR_NO_SHOW',
  OTHER              = 'OTHER',
}

export enum DisputeResolution {
  FULL_DEPOSIT_RETURNED      = 'FULL_DEPOSIT_RETURNED',
  PARTIAL_DEPOSIT_RETURNED   = 'PARTIAL_DEPOSIT_RETURNED',
  DEPOSIT_FORFEITED          = 'DEPOSIT_FORFEITED',
  MUTUAL_AGREEMENT           = 'MUTUAL_AGREEMENT',
  NO_ACTION                  = 'NO_ACTION',
}

export enum NotificationType {
  BOOKING_CONFIRMED           = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED           = 'BOOKING_CANCELLED',
  RENTAL_STARTED              = 'RENTAL_STARTED',
  RETURN_REQUESTED            = 'RETURN_REQUESTED',
  RETURN_CONFIRMED            = 'RETURN_CONFIRMED',
  DEPOSIT_REFUNDED            = 'DEPOSIT_REFUNDED',
  DEPOSIT_DEDUCTED            = 'DEPOSIT_DEDUCTED',
  NEW_REVIEW                  = 'NEW_REVIEW',
  DISPUTE_OPENED              = 'DISPUTE_OPENED',
  DISPUTE_RESOLVED            = 'DISPUTE_RESOLVED',
  PAYMENT_RECEIVED            = 'PAYMENT_RECEIVED',
  PAYOUT_PROCESSED            = 'PAYOUT_PROCESSED',
  VENDOR_APPROVED             = 'VENDOR_APPROVED',
  VENDOR_SUSPENDED            = 'VENDOR_SUSPENDED',
  PRODUCT_AVAILABILITY_ALERT  = 'PRODUCT_AVAILABILITY_ALERT',
  MESSAGE_RECEIVED            = 'MESSAGE_RECEIVED',
}
